language: python

sudo: required
services:
  - docker
env:
  global:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
matrix:
  include:
    - python: "2.7"
      env: PYVER=cp27-cp27m
    - python: "3.4"
      env: PYVER=cp34-cp34m
    - python: "3.5"
      env: PYVER=cp35-cp35m
    - python: "3.6"
      env: PYVER=cp36-cp36m
    - python: "3.7-dev"
      env: PYVER=cp37-cp37m

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PYVER -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
